// Curadoria assistida — LOTE 1 (50 medicamentos essenciais).
// Rascunhos concisos redigidos a partir de fatos farmacológicos consolidados e
// fontes abertas/oficiais (bulas Anvisa/FDA-DailyMed, literatura). NÃO reproduz
// conteúdo proprietário. Entram como reviewed=false (pendentes de validação) —
// o farmacêutico revisa/edita e APROVA na aba Importação antes de virar "Validado".
// Posologias são de ADULTO, referenciais — sempre conferir antes de dispensar.

export type CuratedDraft = {
  ai: string;             // princípio ativo (deve casar com o catálogo)
  gestacao?: string;      // categoria de risco
  indicacoes?: string;
  posologia?: string;
  contraindicacoes?: string;
  ram?: string;           // reações adversas (texto)
};

export const CURADORIA_LOTE_1: CuratedDraft[] = [
  { ai: "Amoxicilina", gestacao: "B", indicacoes: "Infecções bacterianas (respiratórias, otite, ITU, H. pylori em associação).", posologia: "500 mg VO 8/8h ou 875 mg 12/12h; ajustar na insuficiência renal.", contraindicacoes: "Hipersensibilidade a penicilinas/betalactâmicos.", ram: "Diarreia, náusea, candidíase, rash; raro: reação anafilática, colite por C. difficile." },
  { ai: "Amoxicilina + clavulanato de potássio", gestacao: "B", indicacoes: "Infecções por germes produtores de betalactamase (sinusite, otite, ITU, mordeduras).", posologia: "500+125 mg 8/8h ou 875+125 mg 12/12h VO.", contraindicacoes: "Hipersensibilidade a penicilinas; história de icterícia/disfunção hepática com o fármaco.", ram: "Diarreia (comum), náusea, elevação de transaminases, candidíase." },
  { ai: "Azitromicina", gestacao: "B", indicacoes: "Infecções respiratórias, ISTs (clamídia), pele/partes moles.", posologia: "500 mg/dia VO por 3 dias, ou 500 mg no 1º dia e 250 mg/dia por mais 4 dias.", contraindicacoes: "Hipersensibilidade a macrolídeos; disfunção hepática grave.", ram: "Distúrbios GI, prolongamento do QT (cautela), elevação de transaminases." },
  { ai: "Cefalexina", gestacao: "B", indicacoes: "Infecções de pele, ITU, faringoamigdalite estreptocócica.", posologia: "500 mg VO 6/6h a 8/8h.", contraindicacoes: "Hipersensibilidade a cefalosporinas.", ram: "Diarreia, náusea, rash; reação cruzada rara com penicilinas." },
  { ai: "Ceftriaxona", gestacao: "B", indicacoes: "Infecções graves (pneumonia, meningite, pielonefrite, gonorreia).", posologia: "1–2 g/dia IV/IM (meningite até 2 g 12/12h).", contraindicacoes: "Hipersensibilidade a cefalosporinas; neonatos com hiperbilirrubinemia; não coadministrar com soluções de cálcio IV em neonatos.", ram: "Reações no local, diarreia, eosinofilia, pseudolitíase biliar." },
  { ai: "Metronidazol", gestacao: "B", indicacoes: "Infecções anaeróbias, giardíase, amebíase, vaginose, H. pylori.", posologia: "250–500 mg VO 8/8h; até 500 mg IV 8/8h em infecções graves.", contraindicacoes: "1º trimestre (relativo); hipersensibilidade; uso com álcool (efeito dissulfiram).", ram: "Gosto metálico, náusea, neuropatia (uso prolongado), urina escura." },
  { ai: "Nitrofurantoína", gestacao: "B", indicacoes: "ITU baixa não complicada; profilaxia de ITU de repetição.", posologia: "100 mg VO 6/6h por 5–7 dias (formulação de liberação: 100 mg 12/12h).", contraindicacoes: "ClCr < 30–45 mL/min; gestação a termo (38–42 sem); insuficiência renal.", ram: "Náusea, cefaleia, urina amarelo-escura; raro: fibrose pulmonar, neuropatia." },
  { ai: "Sulfametoxazol + trimetoprima", gestacao: "C (D a termo)", indicacoes: "ITU, pneumonia por P. jirovecii, algumas infecções de pele.", posologia: "800+160 mg VO 12/12h (doses maiores na PJP).", contraindicacoes: "Alergia a sulfas; insuficiência renal/hepática grave; anemia megaloblástica por folato; gestação a termo e lactente < 2 meses.", ram: "Rash (inclusive SJS), hipercalemia, mielossupressão, elevação de creatinina." },
  { ai: "Fluconazol", gestacao: "C (dose única B)", indicacoes: "Candidíase (oral, esofágica, vaginal), criptococose.", posologia: "Candidíase vaginal: 150 mg VO dose única; sistêmica: 200–400 mg/dia.", contraindicacoes: "Hipersensibilidade a azóis; uso com fármacos que prolongam QT.", ram: "Náusea, cefaleia, elevação de transaminases, prolongamento do QT." },
  { ai: "Aciclovir", gestacao: "B", indicacoes: "Herpes simples, herpes-zóster, varicela.", posologia: "Herpes-zóster: 800 mg VO 5x/dia por 7 dias; ajustar na insuficiência renal; hidratar.", contraindicacoes: "Hipersensibilidade.", ram: "Náusea, cefaleia; nefrotoxicidade (IV, desidratação), neurotoxicidade em DRC." },
  { ai: "Albendazol", gestacao: "C (contraindicado no 1º tri)", indicacoes: "Helmintíases, neurocisticercose, hidatidose.", posologia: "400 mg VO dose única (helmintos); esquemas prolongados em teníase/neurocisticercose.", contraindicacoes: "Gestação (evitar); hipersensibilidade.", ram: "Dor abdominal, cefaleia; elevação de transaminases e mielossupressão em uso prolongado." },
  { ai: "Ivermectina", gestacao: "C", indicacoes: "Escabiose, pediculose, estrongiloidíase, oncocercose.", posologia: "200 mcg/kg VO dose única (repetir em 1–2 semanas conforme indicação).", contraindicacoes: "Hipersensibilidade; cautela em crianças < 15 kg.", ram: "Prurido, tontura, náusea; reações de Mazzotti em filariose." },
  { ai: "Paracetamol", gestacao: "B", indicacoes: "Dor leve a moderada e febre.", posologia: "500–1000 mg VO 6/6h; máx 3–4 g/dia (menor em hepatopatas/etilistas).", contraindicacoes: "Insuficiência hepática grave; hipersensibilidade.", ram: "Bem tolerado; hepatotoxicidade em superdose; raro: reações cutâneas graves." },
  { ai: "Dipirona sódica", gestacao: "C (evitar 3º tri)", indicacoes: "Dor e febre.", posologia: "500–1000 mg VO/IV 6/6h; máx 4 g/dia.", contraindicacoes: "Discrasias sanguíneas; deficiência de G6PD; hipersensibilidade a pirazolonas.", ram: "Hipotensão (IV rápida); raro mas grave: agranulocitose." },
  { ai: "Ibuprofeno", gestacao: "C (D no 3º tri)", indicacoes: "Dor, febre, inflamação.", posologia: "200–600 mg VO 6/6h–8/8h; máx 1200–2400 mg/dia com alimentos.", contraindicacoes: "Úlcera péptica ativa; DRC avançada; IC descompensada; 3º trimestre; alergia a AINE.", ram: "Dispepsia, sangramento GI, ↑PA, retenção hídrica, lesão renal." },
  { ai: "Diclofenaco", gestacao: "C (D no 3º tri)", indicacoes: "Dor e inflamação musculoesquelética.", posologia: "50 mg VO 8/8h ou 75 mg IM; máx 150 mg/dia, menor tempo possível.", contraindicacoes: "DCV estabelecida (cautela), úlcera ativa, DRC, 3º trimestre, alergia a AINE.", ram: "Dispepsia, sangramento GI, risco cardiovascular, hepatotoxicidade." },
  { ai: "Naproxeno", gestacao: "C (D no 3º tri)", indicacoes: "Dor, inflamação, crises de gota.", posologia: "250–500 mg VO 12/12h com alimentos.", contraindicacoes: "Úlcera ativa, DRC, IC, 3º trimestre, alergia a AINE.", ram: "Dispepsia, sangramento GI, ↑PA, lesão renal." },
  { ai: "Codeína", gestacao: "C", indicacoes: "Dor moderada; tosse (antitussígeno).", posologia: "30–60 mg VO 4/4h–6/6h; máx 240 mg/dia.", contraindicacoes: "Depressão respiratória; < 12 anos; amamentação; metabolizadores ultrarrápidos do CYP2D6.", ram: "Constipação, sonolência, náusea; depressão respiratória em superdose." },
  { ai: "Morfina", gestacao: "C", indicacoes: "Dor intensa (aguda e crônica/oncológica).", posologia: "Titulável; 5–10 mg VO/SC/IV conforme dor e tolerância; ajustar na DRC.", contraindicacoes: "Depressão respiratória, íleo paralítico, hipersensibilidade.", ram: "Constipação, sedação, náusea, prurido; depressão respiratória." },
  { ai: "Captopril", gestacao: "D", indicacoes: "Hipertensão, insuficiência cardíaca, nefroproteção.", posologia: "12,5–50 mg VO 8/8h–12/12h (jejum).", contraindicacoes: "Gestação; angioedema prévio por IECA; estenose bilateral de artéria renal.", ram: "Tosse seca, hipercalemia, hipotensão, ↑creatinina; raro: angioedema." },
  { ai: "Anlodipino", gestacao: "C", indicacoes: "Hipertensão, angina.", posologia: "5–10 mg VO 1x/dia.", contraindicacoes: "Hipersensibilidade; choque cardiogênico.", ram: "Edema de membros inferiores, cefaleia, rubor, tontura." },
  { ai: "Atenolol", gestacao: "D", indicacoes: "Hipertensão, angina, arritmias.", posologia: "25–100 mg VO 1x/dia.", contraindicacoes: "Bradicardia/BAV 2º-3º grau, asma grave, IC descompensada.", ram: "Bradicardia, fadiga, extremidades frias, broncoespasmo, mascara hipoglicemia." },
  { ai: "Propranolol", gestacao: "C", indicacoes: "Hipertensão, arritmias, profilaxia de enxaqueca, tremor, tireotoxicose.", posologia: "40 mg VO 12/12h, titular; enxaqueca 80–160 mg/dia.", contraindicacoes: "Asma/DPOC com broncoespasmo, bradicardia/BAV, IC descompensada.", ram: "Broncoespasmo, bradicardia, fadiga, pesadelos, mascara hipoglicemia." },
  { ai: "Carvedilol", gestacao: "C", indicacoes: "Insuficiência cardíaca, hipertensão, pós-IAM.", posologia: "IC: iniciar 3,125 mg 12/12h e titular lentamente até 25 mg 12/12h.", contraindicacoes: "IC descompensada, asma, bradicardia/BAV, hepatopatia grave.", ram: "Tontura, hipotensão, bradicardia, fadiga." },
  { ai: "Furosemida", gestacao: "C", indicacoes: "Edema (IC, renal, hepático), hipertensão, hipercalemia.", posologia: "20–80 mg VO/IV; titular pela resposta.", contraindicacoes: "Anúria; depleção grave de volume/eletrólitos; hipersensibilidade a sulfonamidas.", ram: "Hipocalemia, hiponatremia, desidratação, hipotensão, ototoxicidade (IV rápida)." },
  { ai: "Atorvastatina", gestacao: "X", indicacoes: "Dislipidemia; prevenção cardiovascular.", posologia: "10–80 mg VO 1x/dia (qualquer horário).", contraindicacoes: "Gestação/lactação; hepatopatia ativa.", ram: "Mialgia, ↑transaminases; raro: rabdomiólise; ↑glicemia." },
  { ai: "Rosuvastatina", gestacao: "X", indicacoes: "Dislipidemia; prevenção cardiovascular.", posologia: "5–40 mg VO 1x/dia.", contraindicacoes: "Gestação/lactação; hepatopatia ativa; cautela em asiáticos (dose).", ram: "Mialgia, ↑transaminases, proteinúria (altas doses); raro: rabdomiólise." },
  { ai: "Levotiroxina sódica", gestacao: "A", indicacoes: "Hipotireoidismo.", posologia: "1,6 mcg/kg/dia VO em jejum; iniciar menor em idosos/cardiopatas; ajustar por TSH.", contraindicacoes: "Tireotoxicose não tratada; IAM agudo.", ram: "Sinais de hipertireoidismo se dose excessiva (taquicardia, tremor, perda de peso)." },
  { ai: "Prednisona", gestacao: "C", indicacoes: "Anti-inflamatório/imunossupressor (asma, alergias, doenças autoimunes).", posologia: "5–60 mg/dia VO conforme indicação; desmame se uso prolongado.", contraindicacoes: "Infecção fúngica sistêmica; hipersensibilidade; cautela em diabetes/HAS/úlcera.", ram: "Hiperglicemia, ↑PA, insônia, ganho de peso, osteoporose, imunossupressão." },
  { ai: "Prednisolona", gestacao: "C", indicacoes: "Corticoterapia sistêmica (inclusive pediatria).", posologia: "5–60 mg/dia VO; forma ativa (não requer ativação hepática).", contraindicacoes: "Infecção fúngica sistêmica; hipersensibilidade.", ram: "Semelhantes à prednisona (metabólicas, GI, imunossupressão)." },
  { ai: "Dexametasona", gestacao: "C", indicacoes: "Anti-inflamatório potente, edema cerebral, antiemético, maturação pulmonar fetal.", posologia: "0,5–8 mg/dia (varia muito com a indicação); IV/VO.", contraindicacoes: "Infecção fúngica sistêmica; hipersensibilidade.", ram: "Hiperglicemia, ↑PA, insônia, imunossupressão, miopatia." },
  { ai: "Hidrocortisona", gestacao: "C", indicacoes: "Insuficiência adrenal, choque, reações alérgicas graves.", posologia: "100–500 mg IV conforme quadro; reposição fisiológica menor.", contraindicacoes: "Infecção fúngica sistêmica; hipersensibilidade.", ram: "Retenção de sódio/edema, hiperglicemia, imunossupressão." },
  { ai: "Salbutamol", gestacao: "C", indicacoes: "Broncoespasmo (asma, DPOC).", posologia: "Inalatório 100–200 mcg conforme necessidade; crises: 4–8 jatos ou nebulização.", contraindicacoes: "Hipersensibilidade.", ram: "Tremor, taquicardia, palpitação, cefaleia, hipocalemia (altas doses)." },
  { ai: "Budesonida", gestacao: "B", indicacoes: "Asma (manutenção), rinite; formas orais em Crohn/colite.", posologia: "Inalatória 200–800 mcg/dia divididos; enxaguar a boca após uso.", contraindicacoes: "Hipersensibilidade.", ram: "Candidíase oral, disfonia, tosse; efeitos sistêmicos em altas doses." },
  { ai: "Loratadina", gestacao: "B", indicacoes: "Rinite alérgica, urticária.", posologia: "10 mg VO 1x/dia.", contraindicacoes: "Hipersensibilidade.", ram: "Cefaleia, sonolência leve, boca seca (baixa sedação)." },
  { ai: "Cetirizina", gestacao: "B", indicacoes: "Rinite alérgica, urticária.", posologia: "10 mg VO 1x/dia (ajustar na DRC).", contraindicacoes: "Hipersensibilidade; DRC grave (ajuste).", ram: "Sonolência (mais que loratadina), boca seca, fadiga." },
  { ai: "Pantoprazol", gestacao: "B", indicacoes: "DRGE, úlcera péptica, proteção gástrica; associado na erradicação de H. pylori.", posologia: "20–40 mg VO 1x/dia antes do café; IV em sangramento.", contraindicacoes: "Hipersensibilidade.", ram: "Cefaleia, diarreia; uso prolongado: hipomagnesemia, ↓B12, fraturas." },
  { ai: "Ondansetrona", gestacao: "B", indicacoes: "Náusea/vômito (quimioterapia, pós-operatório).", posologia: "4–8 mg VO/IV 8/8h.", contraindicacoes: "Uso com apomorfina; prolongamento do QT (cautela).", ram: "Cefaleia, constipação, prolongamento do QT." },
  { ai: "Metoclopramida", gestacao: "B", indicacoes: "Náusea/vômito, gastroparesia, procinético.", posologia: "10 mg VO/IV 8/8h; máx 5 dias (risco extrapiramidal).", contraindicacoes: "Obstrução/perfuração GI, feocromocitoma, epilepsia, Parkinson.", ram: "Sonolência, sintomas extrapiramidais, discinesia tardia (uso prolongado)." },
  { ai: "Escitalopram", gestacao: "C", indicacoes: "Depressão, transtornos de ansiedade.", posologia: "10 mg/dia VO (faixa 5–20 mg).", contraindicacoes: "Uso com IMAO; QT longo (dose-dependente).", ram: "Náusea, insônia, disfunção sexual, hiponatremia (idoso), prolongamento do QT." },
  { ai: "Amitriptilina", gestacao: "C", indicacoes: "Depressão, dor neuropática, profilaxia de enxaqueca.", posologia: "25–75 mg VO à noite (dor: doses menores).", contraindicacoes: "Pós-IAM recente, arritmias, glaucoma de ângulo fechado, uso com IMAO.", ram: "Sedação, boca seca, constipação, retenção urinária, ganho de peso, arritmia (superdose)." },
  { ai: "Diazepam", gestacao: "D", indicacoes: "Ansiedade, espasmo muscular, crises convulsivas, abstinência alcoólica.", posologia: "2–10 mg VO 2–3x/dia; IV em status epilepticus.", contraindicacoes: "Miastenia grave, insuficiência respiratória grave, apneia do sono, hepatopatia grave.", ram: "Sedação, dependência, depressão respiratória (com opioides), quedas em idosos." },
  { ai: "Clonazepam", gestacao: "D", indicacoes: "Epilepsia, transtornos de ansiedade/pânico.", posologia: "0,5 mg VO 2–3x/dia, titular.", contraindicacoes: "Hepatopatia grave, glaucoma de ângulo fechado, insuficiência respiratória grave.", ram: "Sedação, dependência, alterações de comportamento, quedas em idosos." },
  { ai: "Haloperidol", gestacao: "C", indicacoes: "Psicoses, agitação, delirium, náusea refratária.", posologia: "0,5–5 mg VO/IM conforme quadro; menor em idosos.", contraindicacoes: "Parkinson, depressão do SNC grave, QT longo.", ram: "Sintomas extrapiramidais, prolongamento do QT, síndrome neuroléptica maligna (rara)." },
  { ai: "Risperidona", gestacao: "C", indicacoes: "Esquizofrenia, transtorno bipolar, irritabilidade no autismo.", posologia: "1–6 mg/dia VO (iniciar baixo).", contraindicacoes: "Hipersensibilidade; cautela em idoso com demência (↑mortalidade).", ram: "Sintomas extrapiramidais, hiperprolactinemia, ganho de peso, sedação." },
  { ai: "Carbamazepina", gestacao: "D", indicacoes: "Epilepsia (crises focais), neuralgia do trigêmeo, transtorno bipolar.", posologia: "200 mg VO 12/12h, titular; monitorar nível sérico.", contraindicacoes: "BAV, porfiria, mielossupressão, uso com IMAO.", ram: "Sonolência, ataxia, hiponatremia, rash (SJS - risco HLA-B*1502), mielossupressão." },
  { ai: "Ácido valproico", gestacao: "X (teratogênico)", indicacoes: "Epilepsia (amplo espectro), transtorno bipolar, profilaxia de enxaqueca.", posologia: "Iniciar 10–15 mg/kg/dia, titular; monitorar nível e hepática.", contraindicacoes: "Gestação (evitar; teratogênico), hepatopatia, distúrbios do ciclo da ureia.", ram: "Ganho de peso, tremor, queda de cabelo, hepatotoxicidade, trombocitopenia, hiperamonemia." },
  { ai: "Gabapentina", gestacao: "C", indicacoes: "Dor neuropática, epilepsia (adjuvante).", posologia: "Iniciar 300 mg/dia, titular até 900–3600 mg/dia divididos; ajustar na DRC.", contraindicacoes: "Hipersensibilidade.", ram: "Sonolência, tontura, edema, ganho de peso." },
  { ai: "Insulina humana NPH", gestacao: "B", indicacoes: "Diabetes mellitus (controle basal).", posologia: "Dose individualizada por peso/glicemia; geralmente 1–2 aplicações SC/dia.", contraindicacoes: "Hipoglicemia; hipersensibilidade.", ram: "Hipoglicemia, ganho de peso, lipodistrofia no local de aplicação." },
];
