// Terceiro lote do catálogo (DCB). Amplia cobertura: oftalmologia, dermatologia,
// otorrino, vacinas/imunobiológicos, mais oncologia, antídotos e diversos.
// Princípio ativo + classe terapêutica. Campos clínicos vazios (reviewed=false).
import type { BaseDrug } from "./medicamentos-base";

export const BASE_DRUGS_3: BaseDrug[] = [
  // --- Oftalmologia ---
  { ai: "Timolol", tc: "Antiglaucomatoso (betabloqueador tópico)", atc: "S01ED01" },
  { ai: "Latanoprosta", tc: "Antiglaucomatoso (análogo de prostaglandina)", atc: "S01EE01" },
  { ai: "Bimatoprosta", tc: "Antiglaucomatoso (análogo de prostaglandina)", atc: "S01EE03" },
  { ai: "Brimonidina", tc: "Antiglaucomatoso (agonista alfa-2)", atc: "S01EA05" },
  { ai: "Dorzolamida", tc: "Antiglaucomatoso (inibidor da anidrase carbônica)", atc: "S01EC03" },
  { ai: "Tobramicina + dexametasona", tc: "Oftálmico (antibiótico + corticoide)", atc: "S01CA01" },
  { ai: "Moxifloxacino", tc: "Antibacteriano (fluoroquinolona)", atc: "J01MA14" },
  { ai: "Olopatadina", tc: "Antialérgico oftálmico", atc: "S01GX09" },
  { ai: "Ciclopentolato", tc: "Midriático/cicloplégico", atc: "S01FA04" },
  { ai: "Carmelose (lágrima artificial)", tc: "Lubrificante ocular", atc: "S01XA20" },
  // --- Dermatologia ---
  { ai: "Isotretinoína", tc: "Retinoide sistêmico (acne grave)", atc: "D10BA01" },
  { ai: "Tretinoína", tc: "Retinoide tópico", atc: "D10AD01" },
  { ai: "Adapaleno", tc: "Retinoide tópico (acne)", atc: "D10AD03" },
  { ai: "Peróxido de benzoíla", tc: "Antiacneico tópico", atc: "D10AE01" },
  { ai: "Permetrina", tc: "Escabicida/pediculicida", atc: "P03AC04" },
  { ai: "Mupirocina", tc: "Antibacteriano tópico", atc: "D06AX09" },
  { ai: "Ácido salicílico", tc: "Ceratolítico tópico", atc: "D01AE12" },
  { ai: "Calcipotriol", tc: "Antipsoriático tópico (análogo de vit. D)", atc: "D05AX02" },
  { ai: "Hidroquinona", tc: "Despigmentante tópico", atc: "D11AX11" },
  { ai: "Clobetasol", tc: "Corticosteroide tópico de alta potência", atc: "D07AD01" },
  { ai: "Cetoconazol xampu", tc: "Antifúngico tópico (dermatite seborreica)", atc: "D01AC08" },
  { ai: "Minoxidil", tc: "Estimulante do crescimento capilar / vasodilatador", atc: "D11AX01" },
  // --- Otorrino / nasal ---
  { ai: "Budesonida nasal", tc: "Corticosteroide nasal", atc: "R01AD05" },
  { ai: "Mometasona nasal", tc: "Corticosteroide nasal", atc: "R01AD09" },
  { ai: "Oximetazolina", tc: "Descongestionante nasal", atc: "R01AA05" },
  { ai: "Ciprofloxacino otológico", tc: "Antibacteriano otológico", atc: "S02AA15" },
  // --- Vacinas / imunobiológicos ---
  { ai: "Vacina influenza", tc: "Imunizante (gripe)", atc: "J07BB02" },
  { ai: "Vacina hepatite B", tc: "Imunizante", atc: "J07BC01" },
  { ai: "Vacina COVID-19", tc: "Imunizante", atc: "J07BN01" },
  { ai: "Vacina pneumocócica", tc: "Imunizante", atc: "J07AL02" },
  { ai: "Vacina tríplice viral (SCR)", tc: "Imunizante (sarampo/caxumba/rubéola)", atc: "J07BD52" },
  { ai: "Vacina HPV", tc: "Imunizante (papilomavírus)", atc: "J07BM01" },
  { ai: "Vacina dTpa", tc: "Imunizante (difteria/tétano/coqueluche)", atc: "J07AJ52" },
  { ai: "Imunoglobulina humana", tc: "Imunobiológico (imunoglobulina)", atc: "J06BA02" },
  { ai: "Palivizumabe", tc: "Anticorpo monoclonal (VSR)", atc: "J06BD01" },
  { ai: "Omalizumabe", tc: "Imunobiológico (anti-IgE, asma)", atc: "R03DX05" },
  { ai: "Dupilumabe", tc: "Imunobiológico (anti-IL4/IL13)", atc: "D11AH05" },
  { ai: "Ustequinumabe", tc: "Imunobiológico (anti-IL12/23)", atc: "L04AC05" },
  { ai: "Secuquinumabe", tc: "Imunobiológico (anti-IL17)", atc: "L04AC10" },
  // --- Mais oncologia / hematologia ---
  { ai: "Metotrexato oncológico", tc: "Antineoplásico (antimetabólito)", atc: "L01BA01" },
  { ai: "Citarabina", tc: "Antineoplásico (antimetabólito)", atc: "L01BC01" },
  { ai: "Mercaptopurina", tc: "Antineoplásico (antimetabólito)", atc: "L01BB02" },
  { ai: "Vincristina", tc: "Antineoplásico (alcaloide da vinca)", atc: "L01CA02" },
  { ai: "Vimblastina", tc: "Antineoplásico (alcaloide da vinca)", atc: "L01CA01" },
  { ai: "Etoposídeo", tc: "Antineoplásico (inibidor da topoisomerase)", atc: "L01CB01" },
  { ai: "Irinotecano", tc: "Antineoplásico (inibidor da topoisomerase)", atc: "L01CE02" },
  { ai: "Ifosfamida", tc: "Antineoplásico (agente alquilante)", atc: "L01AA06" },
  { ai: "Dacarbazina", tc: "Antineoplásico (agente alquilante)", atc: "L01AX04" },
  { ai: "Bleomicina", tc: "Antineoplásico (antibiótico antitumoral)", atc: "L01DC01" },
  { ai: "Epirrubicina", tc: "Antineoplásico (antraciclina)", atc: "L01DB03" },
  { ai: "Erlotinibe", tc: "Antineoplásico (inibidor de tirosina quinase)", atc: "L01EB02" },
  { ai: "Sunitinibe", tc: "Antineoplásico (inibidor de tirosina quinase)", atc: "L01EX01" },
  { ai: "Sorafenibe", tc: "Antineoplásico (inibidor de tirosina quinase)", atc: "L01EX02" },
  { ai: "Enzalutamida", tc: "Antineoplásico hormonal (câncer de próstata)", atc: "L02BB04" },
  { ai: "Abiraterona", tc: "Antineoplásico hormonal (câncer de próstata)", atc: "L02BX03" },
  { ai: "Leuprorrelina", tc: "Análogo de GnRH (oncologia/endócrino)", atc: "L02AE02" },
  { ai: "Goserrelina", tc: "Análogo de GnRH (oncologia)", atc: "L02AE03" },
  { ai: "Ácido zoledrônico", tc: "Bisfosfonato (metástase óssea/osteoporose)", atc: "M05BA08" },
  { ai: "Denosumabe", tc: "Anticorpo monoclonal (anti-RANKL)", atc: "M05BX04" },
  { ai: "Pegfilgrastim", tc: "Fator estimulador de colônias (G-CSF)", atc: "L03AA13" },
  { ai: "Leucovorina (ácido folínico)", tc: "Resgate/modulador em quimioterapia", atc: "V03AF03" },
  { ai: "Mesna", tc: "Uroprotetor (quimioterapia)", atc: "V03AF01" },
  { ai: "Aprepitanto", tc: "Antiemético (antagonista NK1)", atc: "A04AD12" },
  { ai: "Palonossetrona", tc: "Antiemético (antagonista 5-HT3)", atc: "A04AA05" },
  // --- Antídotos / emergência / toxicologia ---
  { ai: "Flumazenil", tc: "Antídoto (reversor de benzodiazepínicos)", atc: "V03AB25" },
  { ai: "Acetilcisteína (antídoto)", tc: "Antídoto (intoxicação por paracetamol)", atc: "V03AB23" },
  { ai: "Carvão ativado", tc: "Adsorvente (intoxicações)", atc: "A07BA01" },
  { ai: "Sulfato de protamina", tc: "Antídoto (reversor de heparina)", atc: "V03AB14" },
  { ai: "Idarucizumabe", tc: "Antídoto (reversor de dabigatrana)", atc: "V03AB37" },
  { ai: "Atropina", tc: "Anticolinérgico (bradicardia/antídoto)", atc: "A03BA01" },
  { ai: "Glicose hipertônica", tc: "Correção de hipoglicemia", atc: "B05CX01" },
  { ai: "Tiossulfato de sódio", tc: "Antídoto (cianeto)", atc: "V03AB06" },
  { ai: "Deferoxamina", tc: "Quelante de ferro", atc: "V03AC01" },
  // --- Cardiologia / nefrologia adicionais ---
  { ai: "Digoxina imune Fab", tc: "Antídoto (intoxicação digitálica)", atc: "V03AB24" },
  { ai: "Milrinona", tc: "Inotrópico (inibidor de PDE-3)", atc: "C01CE02" },
  { ai: "Levosimendana", tc: "Inotrópico (sensibilizador de cálcio)", atc: "C01CX08" },
  { ai: "Amilorida", tc: "Diurético poupador de potássio", atc: "C03DB01" },
  { ai: "Bumetanida", tc: "Diurético de alça", atc: "C03CA02" },
  { ai: "Torsemida", tc: "Diurético de alça", atc: "C03CA04" },
  { ai: "Nitroprusseto de sódio", tc: "Vasodilatador (emergência hipertensiva)", atc: "C02DD01" },
  { ai: "Alisquireno", tc: "Anti-hipertensivo (inibidor da renina)", atc: "C09XA02" },
  { ai: "Sevelâmer", tc: "Quelante de fósforo (DRC)", atc: "V03AE02" },
  { ai: "Cinacalcete", tc: "Calcimimético (hiperparatireoidismo)", atc: "H05BX01" },
  { ai: "Paricalcitol", tc: "Análogo de vitamina D (DRC)", atc: "H05BX02" },
  // --- Gastro / hepato adicionais ---
  { ai: "Ácido ursodesoxicólico", tc: "Hepatoprotetor/colerético", atc: "A05AA02" },
  { ai: "Ondansetrona orodispersível", tc: "Antiemético (antagonista 5-HT3)", atc: "A04AA01" },
  { ai: "Rifaximina", tc: "Antibacteriano intestinal (não absorvível)", atc: "A07AA11" },
  { ai: "Octreotida LAR", tc: "Análogo da somatostatina (varizes/tumores)", atc: "H01CB02" },
  { ai: "Vonoprazana", tc: "Bloqueador ácido competitivo de potássio (P-CAB)", atc: "A02BC08" },
  // --- Endócrino / metabolismo adicionais ---
  { ai: "Tiratricol", tc: "Análogo tireoidiano", atc: "H03AA04" },
  { ai: "Somatropina", tc: "Hormônio do crescimento", atc: "H01AC01" },
  { ai: "Hidrocortisona (reposição)", tc: "Corticosteroide (insuficiência adrenal)", atc: "H02AB09" },
  { ai: "Fludrocortisona", tc: "Mineralocorticoide", atc: "H02AA02" },
  { ai: "Colestipol", tc: "Hipolipemiante (sequestrante)", atc: "C10AC02" },
  { ai: "Orlistate", tc: "Antiobesidade (inibidor de lipase)", atc: "A08AB01" },
  // --- SNC adicionais ---
  { ai: "Lítio (carbonato)", tc: "Estabilizador do humor", atc: "N05AN01" },
  { ai: "Lurasidona", tc: "Antipsicótico atípico", atc: "N05AE05" },
  { ai: "Modafinila", tc: "Estimulante/promotor de vigília", atc: "N06BA07" },
  { ai: "Metilfenidato", tc: "Psicoestimulante (TDAH)", atc: "N06BA04" },
  { ai: "Lisdexanfetamina", tc: "Psicoestimulante (TDAH)", atc: "N06BA12" },
  { ai: "Atomoxetina", tc: "Não estimulante (TDAH)", atc: "N06BA09" },
  { ai: "Vareniclina", tc: "Cessação do tabagismo", atc: "N07BA03" },
  { ai: "Naltrexona + bupropiona", tc: "Antiobesidade (SNC)", atc: "A08AA62" },
  { ai: "Perampanel", tc: "Anticonvulsivante", atc: "N03AX22" },
  { ai: "Brivaracetam", tc: "Anticonvulsivante", atc: "N03AX23" },
  // --- Respiratório adicionais ---
  { ai: "Umeclidínio + vilanterol", tc: "Broncodilatador duplo (DPOC)", atc: "R03AL03" },
  { ai: "Budesonida + formoterol", tc: "Corticoide inalatório + LABA", atc: "R03AK07" },
  { ai: "Beclometasona + formoterol", tc: "Corticoide inalatório + LABA", atc: "R03AK08" },
  { ai: "Mepolizumabe", tc: "Imunobiológico (anti-IL5, asma eosinofílica)", atc: "R03DX09" },
  { ai: "N-acetilcisteína (respiratório)", tc: "Mucolítico", atc: "R05CB01" },
  // --- Anestesia / dor adicionais ---
  { ai: "Remifentanila", tc: "Analgésico opioide (anestesia)", atc: "N01AH06" },
  { ai: "Sevoflurano", tc: "Anestésico geral inalatório", atc: "N01AB08" },
  { ai: "Ropivacaína", tc: "Anestésico local", atc: "N01BB09" },
  { ai: "Neostigmina", tc: "Anticolinesterásico (reversão de bloqueio)", atc: "N07AA01" },
  { ai: "Dexmedetomidina", tc: "Sedativo (agonista alfa-2)", atc: "N05CM18" },
  { ai: "Etomidato", tc: "Anestésico geral intravenoso", atc: "N01AX07" },
  { ai: "Tiopental", tc: "Anestésico barbitúrico", atc: "N01AF03" },
  // --- Diversos hospitalares ---
  { ai: "Meio de contraste iodado", tc: "Agente de contraste radiológico", atc: "V08AB" },
  { ai: "Gadolínio (contraste)", tc: "Agente de contraste (RM)", atc: "V08CA" },
  { ai: "Albumina humana", tc: "Expansor plasmático / hemoderivado", atc: "B05AA01" },
  { ai: "Ringer lactato", tc: "Solução cristaloide", atc: "B05BB01" },
  { ai: "Cloreto de sódio 0,9%", tc: "Solução cristaloide", atc: "B05BB01" },
  { ai: "Nutrição parenteral", tc: "Suporte nutricional intravenoso", atc: "B05BA10" },
  { ai: "Água para injeção", tc: "Diluente para uso parenteral", atc: "V07AB" },
  { ai: "Surfactante pulmonar", tc: "Surfactante (neonatologia)", atc: "R07AA02" },
  { ai: "Misoprostol", tc: "Análogo de prostaglandina (obstetrícia/gastro)", atc: "G02AD06" },
  { ai: "Ocitocina", tc: "Uterotônico (obstetrícia)", atc: "H01BB02" },
  { ai: "Sulfato de magnésio (obstetrícia)", tc: "Anticonvulsivante (pré-eclâmpsia)", atc: "B05XA05" },
  { ai: "Terbutalina", tc: "Broncodilatador / tocolítico", atc: "R03AC03" },
  { ai: "Nifedipino (tocólise)", tc: "Tocolítico (bloqueador de cálcio)", atc: "C08CA05" },
];
