// Segundo lote do catálogo de medicamentos (DCB / uso hospitalar e ambulatorial).
// Princípio ativo + classe terapêutica (+ ATC quando conhecido). Campos clínicos
// entram vazios (reviewed=false) — curadoria farmacêutica pendente.
import type { BaseDrug } from "./medicamentos-base";

export const BASE_DRUGS_2: BaseDrug[] = [
  // --- Antibacterianos adicionais ---
  { ai: "Cefaclor", tc: "Antibacteriano (cefalosporina 2ª geração)", atc: "J01DC04" },
  { ai: "Cefadroxila", tc: "Antibacteriano (cefalosporina 1ª geração)", atc: "J01DB05" },
  { ai: "Ceftazidima", tc: "Antibacteriano (cefalosporina 3ª geração)", atc: "J01DD02" },
  { ai: "Cefotaxima", tc: "Antibacteriano (cefalosporina 3ª geração)", atc: "J01DD01" },
  { ai: "Ertapeném", tc: "Antibacteriano (carbapenêmico)", atc: "J01DH03" },
  { ai: "Imipeném + cilastatina", tc: "Antibacteriano (carbapenêmico)", atc: "J01DH51" },
  { ai: "Aztreonam", tc: "Antibacteriano (monobactâmico)", atc: "J01DF01" },
  { ai: "Linezolida", tc: "Antibacteriano (oxazolidinona)", atc: "J01XX08" },
  { ai: "Daptomicina", tc: "Antibacteriano (lipopeptídeo)", atc: "J01XX09" },
  { ai: "Teicoplanina", tc: "Antibacteriano (glicopeptídeo)", atc: "J01XA02" },
  { ai: "Polimixina B", tc: "Antibacteriano (polimixina)", atc: "J01XB02" },
  { ai: "Tigeciclina", tc: "Antibacteriano (glicilciclina)", atc: "J01AA12" },
  { ai: "Fosfomicina", tc: "Antibacteriano (fosfônico)", atc: "J01XX01" },
  { ai: "Tobramicina", tc: "Antibacteriano (aminoglicosídeo)", atc: "J01GB01" },
  { ai: "Sulfassalazina", tc: "Anti-inflamatório intestinal / DMARD", atc: "A07EC01" },
  { ai: "Rifampicina", tc: "Antituberculoso (rifamicina)", atc: "J04AB02" },
  { ai: "Isoniazida", tc: "Antituberculoso", atc: "J04AC01" },
  { ai: "Pirazinamida", tc: "Antituberculoso", atc: "J04AK01" },
  { ai: "Etambutol", tc: "Antituberculoso", atc: "J04AK02" },
  { ai: "Claritromicina + amoxicilina + omeprazol", tc: "Terapia de erradicação do H. pylori", atc: "A02BD" },
  // --- Antifúngicos adicionais ---
  { ai: "Voriconazol", tc: "Antifúngico (triazol)", atc: "J02AC03" },
  { ai: "Anidulafungina", tc: "Antifúngico (equinocandina)", atc: "J02AX06" },
  { ai: "Caspofungina", tc: "Antifúngico (equinocandina)", atc: "J02AX04" },
  { ai: "Micafungina", tc: "Antifúngico (equinocandina)", atc: "J02AX05" },
  { ai: "Anfotericina B", tc: "Antifúngico (poliênico)", atc: "J02AA01" },
  { ai: "Miconazol", tc: "Antifúngico (imidazol) tópico", atc: "D01AC02" },
  { ai: "Clotrimazol", tc: "Antifúngico (imidazol) tópico", atc: "D01AC01" },
  // --- Antivirais adicionais ---
  { ai: "Valaciclovir", tc: "Antiviral (análogo de nucleosídeo)", atc: "J05AB11" },
  { ai: "Ganciclovir", tc: "Antiviral (citomegalovírus)", atc: "J05AB06" },
  { ai: "Tenofovir", tc: "Antirretroviral (ITRN)", atc: "J05AF07" },
  { ai: "Lamivudina", tc: "Antirretroviral (ITRN)", atc: "J05AF05" },
  { ai: "Dolutegravir", tc: "Antirretroviral (inibidor de integrase)", atc: "J05AJ03" },
  { ai: "Efavirenz", tc: "Antirretroviral (ITRNN)", atc: "J05AG03" },
  { ai: "Entecavir", tc: "Antiviral (hepatite B)", atc: "J05AF10" },
  // --- Antiparasitários adicionais ---
  { ai: "Nitazoxanida", tc: "Antiparasitário/antiviral", atc: "P01AX11" },
  { ai: "Secnidazol", tc: "Antiprotozoário (nitroimidazol)", atc: "P01AB07" },
  { ai: "Tinidazol", tc: "Antiprotozoário (nitroimidazol)", atc: "P01AB02" },
  { ai: "Pamoato de pirvínio", tc: "Anti-helmíntico", atc: "P02CX01" },
  { ai: "Benznidazol", tc: "Antiparasitário (doença de Chagas)", atc: "P01CA02" },
  { ai: "Cloroquina", tc: "Antimalárico", atc: "P01BA01" },
  { ai: "Artemeter + lumefantrina", tc: "Antimalárico", atc: "P01BF01" },
  // --- Cardiovascular adicionais ---
  { ai: "Lisinopril", tc: "Anti-hipertensivo (IECA)", atc: "C09AA03" },
  { ai: "Perindopril", tc: "Anti-hipertensivo (IECA)", atc: "C09AA04" },
  { ai: "Telmisartana", tc: "Anti-hipertensivo (BRA)", atc: "C09CA07" },
  { ai: "Candesartana", tc: "Anti-hipertensivo (BRA)", atc: "C09CA06" },
  { ai: "Irbesartana", tc: "Anti-hipertensivo (BRA)", atc: "C09CA04" },
  { ai: "Nebivolol", tc: "Betabloqueador vasodilatador", atc: "C07AB12" },
  { ai: "Sotalol", tc: "Antiarrítmico (betabloqueador classe III)", atc: "C07AA07" },
  { ai: "Ivabradina", tc: "Antianginoso (inibidor da corrente If)", atc: "C01EB17" },
  { ai: "Sacubitril + valsartana", tc: "Insuficiência cardíaca (ARNI)", atc: "C09DX04" },
  { ai: "Felodipino", tc: "Bloqueador de canal de cálcio", atc: "C08CA02" },
  { ai: "Lercanidipino", tc: "Bloqueador de canal de cálcio", atc: "C08CA13" },
  { ai: "Nimodipino", tc: "Bloqueador de canal de cálcio (neuro)", atc: "C08CA06" },
  { ai: "Trimetazidina", tc: "Antianginoso metabólico", atc: "C01EB15" },
  { ai: "Dobutamina", tc: "Inotrópico (agonista beta-1)", atc: "C01CA07" },
  { ai: "Noradrenalina", tc: "Vasopressor (catecolamina)", atc: "C01CA03" },
  { ai: "Adrenalina", tc: "Vasopressor/broncodilatador (catecolamina)", atc: "C01CA24" },
  { ai: "Vasopressina", tc: "Vasopressor (análogo de ADH)", atc: "H01BA01" },
  // --- Antitrombóticos adicionais ---
  { ai: "Dabigatrana", tc: "Anticoagulante (inibidor direto da trombina)", atc: "B01AE07" },
  { ai: "Edoxabana", tc: "Anticoagulante (inibidor do fator Xa)", atc: "B01AF03" },
  { ai: "Ticagrelor", tc: "Antiplaquetário (inibidor de P2Y12)", atc: "B01AC24" },
  { ai: "Prasugrel", tc: "Antiplaquetário (inibidor de P2Y12)", atc: "B01AC22" },
  { ai: "Cilostazol", tc: "Antiagregante/vasodilatador", atc: "B01AC23" },
  { ai: "Ácido tranexâmico", tc: "Antifibrinolítico", atc: "B02AA02" },
  { ai: "Alteplase", tc: "Trombolítico (ativador do plasminogênio)", atc: "B01AD02" },
  // --- Hipolipemiantes adicionais ---
  { ai: "Genfibrozila", tc: "Hipolipemiante (fibrato)", atc: "C10AB04" },
  { ai: "Ciprofibrato", tc: "Hipolipemiante (fibrato)", atc: "C10AB08" },
  { ai: "Colestiramina", tc: "Hipolipemiante (sequestrante de ácidos biliares)", atc: "C10AC01" },
  // --- Diabetes / endócrino adicionais ---
  { ai: "Pioglitazona", tc: "Antidiabético (tiazolidinediona)", atc: "A10BG03" },
  { ai: "Acarbose", tc: "Antidiabético (inibidor da alfa-glicosidase)", atc: "A10BF01" },
  { ai: "Repaglinida", tc: "Antidiabético (glinida)", atc: "A10BX02" },
  { ai: "Linagliptina", tc: "Antidiabético (inibidor de DPP-4)", atc: "A10BH05" },
  { ai: "Vildagliptina", tc: "Antidiabético (inibidor de DPP-4)", atc: "A10BH02" },
  { ai: "Canagliflozina", tc: "Antidiabético (inibidor de SGLT2)", atc: "A10BK02" },
  { ai: "Semaglutida", tc: "Antidiabético (análogo de GLP-1)", atc: "A10BJ06" },
  { ai: "Dulaglutida", tc: "Antidiabético (análogo de GLP-1)", atc: "A10BJ05" },
  { ai: "Insulina lispro", tc: "Antidiabético (insulina ultrarrápida)", atc: "A10AB04" },
  { ai: "Insulina asparte", tc: "Antidiabético (insulina ultrarrápida)", atc: "A10AB05" },
  { ai: "Insulina degludeca", tc: "Antidiabético (insulina ultralonga)", atc: "A10AE06" },
  { ai: "Glucagon", tc: "Hormônio (hipoglicemia grave)", atc: "H04AA01" },
  { ai: "Liotironina", tc: "Hormônio tireoidiano (T3)", atc: "H03AA02" },
  { ai: "Cabergolina", tc: "Agonista dopaminérgico (prolactina)", atc: "G02CB03" },
  { ai: "Bromocriptina", tc: "Agonista dopaminérgico", atc: "N04BC01" },
  { ai: "Desmopressina", tc: "Análogo de vasopressina (diabetes insipidus)", atc: "H01BA02" },
  { ai: "Octreotida", tc: "Análogo da somatostatina", atc: "H01CB02" },
  // --- Saúde da mulher/homem e hormônios ---
  { ai: "Etinilestradiol + levonorgestrel", tc: "Contraceptivo hormonal combinado", atc: "G03AA07" },
  { ai: "Levonorgestrel", tc: "Progestágeno (contracepção)", atc: "G03AC03" },
  { ai: "Medroxiprogesterona", tc: "Progestágeno", atc: "G03AC06" },
  { ai: "Estradiol", tc: "Estrogênio (terapia hormonal)", atc: "G03CA03" },
  { ai: "Tibolona", tc: "Terapia hormonal (esteroide sintético)", atc: "G03CX01" },
  { ai: "Dutasterida", tc: "Inibidor da 5-alfa-redutase", atc: "G04CB02" },
  { ai: "Doxazosina", tc: "Alfabloqueador", atc: "G04CA53" },
  { ai: "Tadalafila", tc: "Inibidor da fosfodiesterase-5", atc: "G04BE08" },
  { ai: "Solifenacina", tc: "Antimuscarínico (bexiga hiperativa)", atc: "G04BD08" },
  { ai: "Mirabegrona", tc: "Agonista beta-3 (bexiga hiperativa)", atc: "G04BD12" },
  // --- Gastrointestinal adicionais ---
  { ai: "Lansoprazol", tc: "Inibidor da bomba de prótons (IBP)", atc: "A02BC03" },
  { ai: "Rabeprazol", tc: "Inibidor da bomba de prótons (IBP)", atc: "A02BC04" },
  { ai: "Famotidina", tc: "Antagonista H2", atc: "A02BA03" },
  { ai: "Sucralfato", tc: "Protetor de mucosa", atc: "A02BX02" },
  { ai: "Mesalazina", tc: "Anti-inflamatório intestinal (5-ASA)", atc: "A07EC02" },
  { ai: "Racecadotrila", tc: "Antidiarreico (inibidor da encefalinase)", atc: "A07XA04" },
  { ai: "Polietilenoglicol", tc: "Laxante osmótico", atc: "A06AD15" },
  { ai: "Bisacodil", tc: "Laxante estimulante", atc: "A06AB02" },
  { ai: "Picossulfato de sódio", tc: "Laxante estimulante", atc: "A06AB08" },
  { ai: "Prometazina", tc: "Anti-histamínico/antiemético (1ª geração)", atc: "R06AD02" },
  { ai: "Dimenidrinato", tc: "Antiemético (cinetose)", atc: "R06AA02" },
  // --- Respiratório / alergia adicionais ---
  { ai: "Tiotrópio", tc: "Broncodilatador (anticolinérgico de longa ação)", atc: "R03BB04" },
  { ai: "Salmeterol + fluticasona", tc: "Broncodilatador + corticosteroide inalatório", atc: "R03AK06" },
  { ai: "Fluticasona", tc: "Corticosteroide inalatório/nasal", atc: "R03BA05" },
  { ai: "Mometasona", tc: "Corticosteroide nasal/inalatório", atc: "R01AD09" },
  { ai: "Roflumilaste", tc: "Anti-inflamatório (inibidor de PDE-4) na DPOC", atc: "R03DX07" },
  { ai: "Fexofenadina", tc: "Anti-histamínico (2ª geração)", atc: "R06AX26" },
  { ai: "Bilastina", tc: "Anti-histamínico (2ª geração)", atc: "R06AX29" },
  { ai: "Ebastina", tc: "Anti-histamínico (2ª geração)", atc: "R06AX22" },
  { ai: "Rupatadina", tc: "Anti-histamínico (2ª geração)", atc: "R06AX28" },
  { ai: "Hidroxizina", tc: "Anti-histamínico/ansiolítico (1ª geração)", atc: "N05BB01" },
  // --- SNC adicionais ---
  { ai: "Fluvoxamina", tc: "Antidepressivo (ISRS)", atc: "N06AB08" },
  { ai: "Trazodona", tc: "Antidepressivo (SARI)", atc: "N06AX05" },
  { ai: "Vortioxetina", tc: "Antidepressivo multimodal", atc: "N06AX26" },
  { ai: "Desvenlafaxina", tc: "Antidepressivo (IRSN)", atc: "N06AX23" },
  { ai: "Imipramina", tc: "Antidepressivo tricíclico", atc: "N06AA02" },
  { ai: "Clomipramina", tc: "Antidepressivo tricíclico", atc: "N06AA04" },
  { ai: "Aripiprazol", tc: "Antipsicótico atípico", atc: "N05AX12" },
  { ai: "Ziprasidona", tc: "Antipsicótico atípico", atc: "N05AE04" },
  { ai: "Clozapina", tc: "Antipsicótico atípico", atc: "N05AH02" },
  { ai: "Paliperidona", tc: "Antipsicótico atípico", atc: "N05AX13" },
  { ai: "Sulpirida", tc: "Antipsicótico (benzamida)", atc: "N05AL01" },
  { ai: "Zolpidem", tc: "Hipnótico (não benzodiazepínico)", atc: "N05CF02" },
  { ai: "Buspirona", tc: "Ansiolítico (não benzodiazepínico)", atc: "N05BE01" },
  { ai: "Lorazepam", tc: "Benzodiazepínico (ansiolítico)", atc: "N05BA06" },
  { ai: "Oxcarbazepina", tc: "Anticonvulsivante", atc: "N03AF02" },
  { ai: "Clobazam", tc: "Benzodiazepínico (anticonvulsivante)", atc: "N05BA09" },
  { ai: "Donepezila", tc: "Anticolinesterásico (Alzheimer)", atc: "N06DA02" },
  { ai: "Rivastigmina", tc: "Anticolinesterásico (Alzheimer)", atc: "N06DA03" },
  { ai: "Memantina", tc: "Antagonista NMDA (Alzheimer)", atc: "N06DX01" },
  { ai: "Pramipexol", tc: "Agonista dopaminérgico (Parkinson)", atc: "N04BC05" },
  { ai: "Sumatriptano", tc: "Antienxaqueca (triptano)", atc: "N02CC01" },
  { ai: "Flunarizina", tc: "Profilaxia de enxaqueca/vertigem", atc: "N07CA03" },
  // --- Analgésicos / relaxantes adicionais ---
  { ai: "Buprenorfina", tc: "Analgésico opioide (agonista parcial)", atc: "N02AE01" },
  { ai: "Tapentadol", tc: "Analgésico opioide de ação central", atc: "N02AX06" },
  { ai: "Naloxona", tc: "Antagonista opioide", atc: "V03AB15" },
  { ai: "Cetorolaco", tc: "Anti-inflamatório não esteroide (AINE)", atc: "M01AB15" },
  { ai: "Etoricoxibe", tc: "Anti-inflamatório (inibidor seletivo de COX-2)", atc: "M01AH05" },
  { ai: "Ciclobenzaprina", tc: "Relaxante muscular", atc: "M03BX08" },
  { ai: "Baclofeno", tc: "Relaxante muscular (agonista GABA-B)", atc: "M03BX01" },
  { ai: "Tizanidina", tc: "Relaxante muscular (agonista alfa-2)", atc: "M03BX02" },
  { ai: "Orfenadrina", tc: "Relaxante muscular", atc: "M03BC01" },
  // --- Reumatologia / imunobiológicos ---
  { ai: "Febuxostate", tc: "Hipouricemiante (inibidor da xantina oxidase)", atc: "M04AA03" },
  { ai: "Adalimumabe", tc: "Imunobiológico (anti-TNF)", atc: "L04AB04" },
  { ai: "Etanercepte", tc: "Imunobiológico (anti-TNF)", atc: "L04AB01" },
  { ai: "Infliximabe", tc: "Imunobiológico (anti-TNF)", atc: "L04AB02" },
  { ai: "Tocilizumabe", tc: "Imunobiológico (anti-IL6)", atc: "L04AC07" },
  { ai: "Rituximabe", tc: "Anticorpo monoclonal (anti-CD20)", atc: "L01FA01" },
  { ai: "Tofacitinibe", tc: "Imunossupressor (inibidor de JAK)", atc: "L04AA29" },
  { ai: "Micofenolato de mofetila", tc: "Imunossupressor", atc: "L04AA06" },
  // --- Oncologia (perfil hospitalar) ---
  { ai: "Cisplatina", tc: "Antineoplásico (platina)", atc: "L01XA01" },
  { ai: "Carboplatina", tc: "Antineoplásico (platina)", atc: "L01XA02" },
  { ai: "Oxaliplatina", tc: "Antineoplásico (platina)", atc: "L01XA03" },
  { ai: "Paclitaxel", tc: "Antineoplásico (taxano)", atc: "L01CD01" },
  { ai: "Docetaxel", tc: "Antineoplásico (taxano)", atc: "L01CD02" },
  { ai: "Doxorrubicina", tc: "Antineoplásico (antraciclina)", atc: "L01DB01" },
  { ai: "Ciclofosfamida", tc: "Antineoplásico (agente alquilante)", atc: "L01AA01" },
  { ai: "Fluoruracila", tc: "Antineoplásico (antimetabólito)", atc: "L01BC02" },
  { ai: "Capecitabina", tc: "Antineoplásico (antimetabólito oral)", atc: "L01BC06" },
  { ai: "Gemcitabina", tc: "Antineoplásico (antimetabólito)", atc: "L01BC05" },
  { ai: "Imatinibe", tc: "Antineoplásico (inibidor de tirosina quinase)", atc: "L01EA01" },
  { ai: "Trastuzumabe", tc: "Anticorpo monoclonal (anti-HER2)", atc: "L01FD01" },
  { ai: "Bevacizumabe", tc: "Anticorpo monoclonal (anti-VEGF)", atc: "L01FG01" },
  { ai: "Pembrolizumabe", tc: "Imunoterapia (anti-PD-1)", atc: "L01FF02" },
  { ai: "Nivolumabe", tc: "Imunoterapia (anti-PD-1)", atc: "L01FF01" },
  { ai: "Tamoxifeno", tc: "Antineoplásico hormonal (SERM)", atc: "L02BA01" },
  { ai: "Anastrozol", tc: "Antineoplásico hormonal (inibidor de aromatase)", atc: "L02BG03" },
  { ai: "Letrozol", tc: "Antineoplásico hormonal (inibidor de aromatase)", atc: "L02BG04" },
  { ai: "Ondansetrona + palonossetrona", tc: "Antiemético (quimioterapia)", atc: "A04AA" },
  // --- Suporte / hematologia / vitaminas ---
  { ai: "Alfaepoetina", tc: "Eritropoetina (antianêmico)", atc: "B03XA01" },
  { ai: "Filgrastim", tc: "Fator estimulador de colônias (G-CSF)", atc: "L03AA02" },
  { ai: "Complexo B", tc: "Suplemento vitamínico", atc: "A11EA" },
  { ai: "Tiamina (vitamina B1)", tc: "Vitamina", atc: "A11DA01" },
  { ai: "Piridoxina (vitamina B6)", tc: "Vitamina", atc: "A11HA02" },
  { ai: "Retinol (vitamina A)", tc: "Vitamina", atc: "A11CA01" },
  { ai: "Tocoferol (vitamina E)", tc: "Vitamina", atc: "A11HA03" },
  { ai: "Fitomenadiona (vitamina K)", tc: "Vitamina/antifibrinolítico", atc: "B02BA01" },
  { ai: "Sulfato de zinco", tc: "Suplemento mineral", atc: "A12CB01" },
  { ai: "Sulfato de magnésio", tc: "Suplemento mineral/anticonvulsivante", atc: "B05XA05" },
  { ai: "Cloreto de potássio", tc: "Reposição eletrolítica", atc: "B05XA01" },
  { ai: "Gluconato de cálcio", tc: "Reposição eletrolítica", atc: "A12AA03" },
  { ai: "Soro de reidratação oral", tc: "Reidratação (sais)", atc: "A07CA" },
  // --- Diversos hospitalares ---
  { ai: "Acetazolamida", tc: "Inibidor da anidrase carbônica (diurético/glaucoma)", atc: "S01EC01" },
  { ai: "Manitol", tc: "Diurético osmótico", atc: "B05BC01" },
  { ai: "Sevelâmer", tc: "Quelante de fósforo (DRC)", atc: "V03AE02" },
  { ai: "Naloxona + oxicodona", tc: "Analgésico opioide (associação)", atc: "N02AA55" },
  { ai: "Sugammadex", tc: "Reversor de bloqueio neuromuscular", atc: "V03AB35" },
  { ai: "Propofol", tc: "Anestésico geral intravenoso", atc: "N01AX10" },
  { ai: "Rocurônio", tc: "Bloqueador neuromuscular", atc: "M03AC09" },
  { ai: "Lidocaína", tc: "Anestésico local/antiarrítmico", atc: "N01BB02" },
  { ai: "Bupivacaína", tc: "Anestésico local", atc: "N01BB01" },
  { ai: "Cetamina", tc: "Anestésico dissociativo", atc: "N01AX03" },
];
