// Catálogo de medicamentos essenciais (nomenclatura DCB / linha RENAME).
// Contém princípio ativo + classe terapêutica (+ ATC quando conhecido).
// Campos clínicos (posologia, interações, RAM) ficam VAZIOS e devem ser
// curados/validados por farmacêutico — por isso entram com reviewed=false.
// Fonte: nomenclatura pública (DCB/Anvisa, RENAME). Fatos não protegidos por direito autoral.

export type BaseDrug = { ai: string; tc: string; atc?: string; preg?: string };

export const BASE_DRUGS: BaseDrug[] = [
  // Antibacterianos
  { ai: "Amoxicilina", tc: "Antibacteriano (penicilina)", atc: "J01CA04" },
  { ai: "Amoxicilina + clavulanato de potássio", tc: "Antibacteriano (penicilina + inibidor de betalactamase)", atc: "J01CR02" },
  { ai: "Ampicilina", tc: "Antibacteriano (penicilina)", atc: "J01CA01" },
  { ai: "Benzilpenicilina benzatina", tc: "Antibacteriano (penicilina)", atc: "J01CE08" },
  { ai: "Oxacilina", tc: "Antibacteriano (penicilina antiestafilocócica)", atc: "J01CF04" },
  { ai: "Azitromicina", tc: "Antibacteriano (macrolídeo)", atc: "J01FA10" },
  { ai: "Eritromicina", tc: "Antibacteriano (macrolídeo)", atc: "J01FA01" },
  { ai: "Cefalexina", tc: "Antibacteriano (cefalosporina 1ª geração)", atc: "J01DB01" },
  { ai: "Cefazolina", tc: "Antibacteriano (cefalosporina 1ª geração)", atc: "J01DB04" },
  { ai: "Cefuroxima", tc: "Antibacteriano (cefalosporina 2ª geração)", atc: "J01DC02" },
  { ai: "Ceftriaxona", tc: "Antibacteriano (cefalosporina 3ª geração)", atc: "J01DD04" },
  { ai: "Cefepima", tc: "Antibacteriano (cefalosporina 4ª geração)", atc: "J01DE01" },
  { ai: "Clindamicina", tc: "Antibacteriano (lincosamida)", atc: "J01FF01" },
  { ai: "Doxiciclina", tc: "Antibacteriano (tetraciclina)", atc: "J01AA02" },
  { ai: "Tetraciclina", tc: "Antibacteriano (tetraciclina)", atc: "J01AA07" },
  { ai: "Gentamicina", tc: "Antibacteriano (aminoglicosídeo)", atc: "J01GB03" },
  { ai: "Amicacina", tc: "Antibacteriano (aminoglicosídeo)", atc: "J01GB06" },
  { ai: "Levofloxacino", tc: "Antibacteriano (fluoroquinolona)", atc: "J01MA12" },
  { ai: "Norfloxacino", tc: "Antibacteriano (fluoroquinolona)", atc: "J01MA06" },
  { ai: "Metronidazol", tc: "Antibacteriano/antiprotozoário (nitroimidazol)", atc: "J01XD01" },
  { ai: "Nitrofurantoína", tc: "Antibacteriano (nitrofurano)", atc: "J01XE01" },
  { ai: "Sulfametoxazol + trimetoprima", tc: "Antibacteriano (sulfonamida)", atc: "J01EE01" },
  { ai: "Vancomicina", tc: "Antibacteriano (glicopeptídeo)", atc: "J01XA01" },
  { ai: "Meropeném", tc: "Antibacteriano (carbapenêmico)", atc: "J01DH02" },
  { ai: "Piperacilina + tazobactam", tc: "Antibacteriano (penicilina + inibidor de betalactamase)", atc: "J01CR05" },
  // Antifúngicos / antivirais / antiparasitários
  { ai: "Fluconazol", tc: "Antifúngico (triazol)", atc: "J02AC01" },
  { ai: "Itraconazol", tc: "Antifúngico (triazol)", atc: "J02AC02" },
  { ai: "Cetoconazol", tc: "Antifúngico (imidazol)", atc: "J02AB02" },
  { ai: "Nistatina", tc: "Antifúngico (poliênico)", atc: "A07AA02" },
  { ai: "Terbinafina", tc: "Antifúngico (alilamina)", atc: "D01BA02" },
  { ai: "Aciclovir", tc: "Antiviral (análogo de nucleosídeo)", atc: "J05AB01" },
  { ai: "Oseltamivir", tc: "Antiviral (inibidor de neuraminidase)", atc: "J05AH02" },
  { ai: "Albendazol", tc: "Antiparasitário (anti-helmíntico)", atc: "P02CA03" },
  { ai: "Mebendazol", tc: "Antiparasitário (anti-helmíntico)", atc: "P02CA01" },
  { ai: "Ivermectina", tc: "Antiparasitário (avermectina)", atc: "P02CF01" },
  { ai: "Praziquantel", tc: "Antiparasitário (anti-helmíntico)", atc: "P02BA01" },
  // Analgésicos, antitérmicos e AINEs
  { ai: "Paracetamol", tc: "Analgésico/antitérmico", atc: "N02BE01" },
  { ai: "Dipirona sódica", tc: "Analgésico/antitérmico (pirazolona)", atc: "N02BB02" },
  { ai: "Ibuprofeno", tc: "Anti-inflamatório não esteroide (AINE)", atc: "M01AE01" },
  { ai: "Naproxeno", tc: "Anti-inflamatório não esteroide (AINE)", atc: "M01AE02" },
  { ai: "Diclofenaco", tc: "Anti-inflamatório não esteroide (AINE)", atc: "M01AB05" },
  { ai: "Cetoprofeno", tc: "Anti-inflamatório não esteroide (AINE)", atc: "M01AE03" },
  { ai: "Nimesulida", tc: "Anti-inflamatório não esteroide (AINE)", atc: "M01AX17" },
  { ai: "Meloxicam", tc: "Anti-inflamatório não esteroide (AINE)", atc: "M01AC06" },
  { ai: "Celecoxibe", tc: "Anti-inflamatório (inibidor seletivo de COX-2)", atc: "M01AH01" },
  { ai: "Piroxicam", tc: "Anti-inflamatório não esteroide (AINE)", atc: "M01AC01" },
  { ai: "Colchicina", tc: "Antigotoso", atc: "M04AC01" },
  // Opioides
  { ai: "Morfina", tc: "Analgésico opioide", atc: "N02AA01" },
  { ai: "Codeína", tc: "Analgésico opioide", atc: "R05DA04" },
  { ai: "Fentanila", tc: "Analgésico opioide", atc: "N01AH01" },
  { ai: "Metadona", tc: "Analgésico opioide", atc: "N07BC02" },
  { ai: "Oxicodona", tc: "Analgésico opioide", atc: "N02AA05" },
  // Cardiovascular / anti-hipertensivos
  { ai: "Captopril", tc: "Anti-hipertensivo (IECA)", atc: "C09AA01" },
  { ai: "Ramipril", tc: "Anti-hipertensivo (IECA)", atc: "C09AA05" },
  { ai: "Valsartana", tc: "Anti-hipertensivo (BRA)", atc: "C09CA03" },
  { ai: "Olmesartana", tc: "Anti-hipertensivo (BRA)", atc: "C09CA08" },
  { ai: "Anlodipino", tc: "Anti-hipertensivo (bloqueador de canal de cálcio)", atc: "C08CA01" },
  { ai: "Nifedipino", tc: "Anti-hipertensivo (bloqueador de canal de cálcio)", atc: "C08CA05" },
  { ai: "Diltiazem", tc: "Antianginoso/antiarrítmico (bloqueador de cálcio)", atc: "C08DB01" },
  { ai: "Verapamil", tc: "Antiarrítmico (bloqueador de cálcio)", atc: "C08DA01" },
  { ai: "Atenolol", tc: "Betabloqueador", atc: "C07AB03" },
  { ai: "Propranolol", tc: "Betabloqueador", atc: "C07AA05" },
  { ai: "Metoprolol", tc: "Betabloqueador", atc: "C07AB02" },
  { ai: "Carvedilol", tc: "Betabloqueador (com ação alfa)", atc: "C07AG02" },
  { ai: "Bisoprolol", tc: "Betabloqueador", atc: "C07AB07" },
  { ai: "Furosemida", tc: "Diurético de alça", atc: "C03CA01" },
  { ai: "Clortalidona", tc: "Diurético tiazídico-símile", atc: "C03BA04" },
  { ai: "Indapamida", tc: "Diurético tiazídico-símile", atc: "C03BA11" },
  { ai: "Metildopa", tc: "Anti-hipertensivo de ação central", atc: "C02AB01" },
  { ai: "Clonidina", tc: "Anti-hipertensivo de ação central", atc: "C02AC01" },
  { ai: "Hidralazina", tc: "Vasodilatador anti-hipertensivo", atc: "C02DB02" },
  { ai: "Isossorbida, mononitrato", tc: "Vasodilatador (nitrato)", atc: "C01DA14" },
  { ai: "Propafenona", tc: "Antiarrítmico classe IC", atc: "C01BC03" },
  // Hipolipemiantes / antitrombóticos
  { ai: "Atorvastatina", tc: "Hipolipemiante (estatina)", atc: "C10AA05" },
  { ai: "Rosuvastatina", tc: "Hipolipemiante (estatina)", atc: "C10AA07" },
  { ai: "Pravastatina", tc: "Hipolipemiante (estatina)", atc: "C10AA03" },
  { ai: "Ezetimiba", tc: "Hipolipemiante (inibidor de absorção)", atc: "C10AX09" },
  { ai: "Fenofibrato", tc: "Hipolipemiante (fibrato)", atc: "C10AB05" },
  { ai: "Rivaroxabana", tc: "Anticoagulante oral (inibidor do fator Xa)", atc: "B01AF01" },
  { ai: "Apixabana", tc: "Anticoagulante oral (inibidor do fator Xa)", atc: "B01AF02" },
  { ai: "Enoxaparina", tc: "Anticoagulante (heparina de baixo peso molecular)", atc: "B01AB05" },
  { ai: "Heparina", tc: "Anticoagulante", atc: "B01AB01" },
  // Diabetes / endócrino
  { ai: "Glibenclamida", tc: "Antidiabético (sulfonilureia)", atc: "A10BB01" },
  { ai: "Gliclazida", tc: "Antidiabético (sulfonilureia)", atc: "A10BB09" },
  { ai: "Glimepirida", tc: "Antidiabético (sulfonilureia)", atc: "A10BB12" },
  { ai: "Insulina humana NPH", tc: "Antidiabético (insulina intermediária)", atc: "A10AC01" },
  { ai: "Insulina humana regular", tc: "Antidiabético (insulina rápida)", atc: "A10AB01" },
  { ai: "Insulina glargina", tc: "Antidiabético (insulina de ação prolongada)", atc: "A10AE04" },
  { ai: "Dapagliflozina", tc: "Antidiabético (inibidor de SGLT2)", atc: "A10BK01" },
  { ai: "Empagliflozina", tc: "Antidiabético (inibidor de SGLT2)", atc: "A10BK03" },
  { ai: "Sitagliptina", tc: "Antidiabético (inibidor de DPP-4)", atc: "A10BH01" },
  { ai: "Liraglutida", tc: "Antidiabético (análogo de GLP-1)", atc: "A10BJ02" },
  { ai: "Levotiroxina sódica", tc: "Hormônio tireoidiano", atc: "H03AA01" },
  { ai: "Metimazol", tc: "Antitireoidiano", atc: "H03BB02" },
  { ai: "Propiltiouracil", tc: "Antitireoidiano", atc: "H03BA02" },
  // Corticosteroides
  { ai: "Prednisona", tc: "Corticosteroide sistêmico", atc: "H02AB07" },
  { ai: "Prednisolona", tc: "Corticosteroide sistêmico", atc: "H02AB06" },
  { ai: "Dexametasona", tc: "Corticosteroide sistêmico", atc: "H02AB02" },
  { ai: "Hidrocortisona", tc: "Corticosteroide sistêmico", atc: "H02AB09" },
  { ai: "Metilprednisolona", tc: "Corticosteroide sistêmico", atc: "H02AB04" },
  { ai: "Betametasona", tc: "Corticosteroide sistêmico/tópico", atc: "H02AB01" },
  // Gastrointestinal
  { ai: "Pantoprazol", tc: "Inibidor da bomba de prótons (IBP)", atc: "A02BC02" },
  { ai: "Esomeprazol", tc: "Inibidor da bomba de prótons (IBP)", atc: "A02BC05" },
  { ai: "Ranitidina", tc: "Antagonista H2", atc: "A02BA02" },
  { ai: "Domperidona", tc: "Procinético/antiemético", atc: "A03FA03" },
  { ai: "Metoclopramida", tc: "Procinético/antiemético", atc: "A03FA01" },
  { ai: "Bromoprida", tc: "Procinético/antiemético", atc: "A03FA04" },
  { ai: "Ondansetrona", tc: "Antiemético (antagonista 5-HT3)", atc: "A04AA01" },
  { ai: "Escopolamina (hioscina)", tc: "Antiespasmódico", atc: "A03BB01" },
  { ai: "Simeticona", tc: "Antiflatulento", atc: "A03AX13" },
  { ai: "Lactulose", tc: "Laxante osmótico", atc: "A06AD11" },
  { ai: "Loperamida", tc: "Antidiarreico", atc: "A07DA03" },
  // Respiratório / antialérgicos
  { ai: "Salbutamol", tc: "Broncodilatador (beta-2 agonista de curta ação)", atc: "R03AC02" },
  { ai: "Formoterol", tc: "Broncodilatador (beta-2 agonista de longa ação)", atc: "R03AC13" },
  { ai: "Budesonida", tc: "Corticosteroide inalatório", atc: "R03BA02" },
  { ai: "Beclometasona", tc: "Corticosteroide inalatório", atc: "R03BA01" },
  { ai: "Brometo de ipratrópio", tc: "Broncodilatador (anticolinérgico)", atc: "R03BB01" },
  { ai: "Montelucaste", tc: "Antiasmático (antileucotrieno)", atc: "R03DC03" },
  { ai: "Loratadina", tc: "Anti-histamínico (2ª geração)", atc: "R06AX13" },
  { ai: "Desloratadina", tc: "Anti-histamínico (2ª geração)", atc: "R06AX27" },
  { ai: "Cetirizina", tc: "Anti-histamínico (2ª geração)", atc: "R06AE07" },
  { ai: "Dexclorfeniramina", tc: "Anti-histamínico (1ª geração)", atc: "R06AB02" },
  { ai: "Ambroxol", tc: "Mucolítico/expectorante", atc: "R05CB06" },
  { ai: "Acetilcisteína", tc: "Mucolítico", atc: "R05CB01" },
  // Sistema nervoso central
  { ai: "Escitalopram", tc: "Antidepressivo (ISRS)", atc: "N06AB10" },
  { ai: "Paroxetina", tc: "Antidepressivo (ISRS)", atc: "N06AB05" },
  { ai: "Citalopram", tc: "Antidepressivo (ISRS)", atc: "N06AB04" },
  { ai: "Amitriptilina", tc: "Antidepressivo tricíclico", atc: "N06AA09" },
  { ai: "Nortriptilina", tc: "Antidepressivo tricíclico", atc: "N06AA10" },
  { ai: "Venlafaxina", tc: "Antidepressivo (IRSN)", atc: "N06AX16" },
  { ai: "Duloxetina", tc: "Antidepressivo (IRSN)", atc: "N06AX21" },
  { ai: "Bupropiona", tc: "Antidepressivo (inibidor de recaptação de dopamina/noradrenalina)", atc: "N06AX12" },
  { ai: "Mirtazapina", tc: "Antidepressivo (noradrenérgico/serotoninérgico específico)", atc: "N06AX11" },
  { ai: "Diazepam", tc: "Benzodiazepínico (ansiolítico)", atc: "N05BA01" },
  { ai: "Clonazepam", tc: "Benzodiazepínico (anticonvulsivante/ansiolítico)", atc: "N03AE01" },
  { ai: "Alprazolam", tc: "Benzodiazepínico (ansiolítico)", atc: "N05BA12" },
  { ai: "Bromazepam", tc: "Benzodiazepínico (ansiolítico)", atc: "N05BA08" },
  { ai: "Midazolam", tc: "Benzodiazepínico (sedativo)", atc: "N05CD08" },
  { ai: "Haloperidol", tc: "Antipsicótico típico", atc: "N05AD01" },
  { ai: "Risperidona", tc: "Antipsicótico atípico", atc: "N05AX08" },
  { ai: "Quetiapina", tc: "Antipsicótico atípico", atc: "N05AH04" },
  { ai: "Olanzapina", tc: "Antipsicótico atípico", atc: "N05AH03" },
  { ai: "Clorpromazina", tc: "Antipsicótico típico", atc: "N05AA01" },
  { ai: "Ácido valproico", tc: "Anticonvulsivante", atc: "N03AG01" },
  { ai: "Carbamazepina", tc: "Anticonvulsivante", atc: "N03AF01" },
  { ai: "Fenobarbital", tc: "Anticonvulsivante (barbitúrico)", atc: "N03AA02" },
  { ai: "Lamotrigina", tc: "Anticonvulsivante", atc: "N03AX09" },
  { ai: "Gabapentina", tc: "Anticonvulsivante/analgésico neuropático", atc: "N03AX12" },
  { ai: "Pregabalina", tc: "Anticonvulsivante/analgésico neuropático", atc: "N03AX16" },
  { ai: "Levetiracetam", tc: "Anticonvulsivante", atc: "N03AX14" },
  { ai: "Topiramato", tc: "Anticonvulsivante", atc: "N03AX11" },
  { ai: "Levodopa + carbidopa", tc: "Antiparkinsoniano", atc: "N04BA02" },
  { ai: "Biperideno", tc: "Antiparkinsoniano (anticolinérgico)", atc: "N04AA02" },
  // Urologia / saúde da mulher e homem
  { ai: "Tansulosina", tc: "Alfabloqueador (hiperplasia prostática)", atc: "G04CA02" },
  { ai: "Finasterida", tc: "Inibidor da 5-alfa-redutase", atc: "G04CB01" },
  { ai: "Sildenafila", tc: "Inibidor da fosfodiesterase-5", atc: "G04BE03" },
  { ai: "Oxibutinina", tc: "Antimuscarínico (bexiga hiperativa)", atc: "G04BD04" },
  // Osso / vitaminas / suplementos
  { ai: "Alendronato de sódio", tc: "Bisfosfonato (osteoporose)", atc: "M05BA04" },
  { ai: "Colecalciferol (vitamina D3)", tc: "Vitamina / suplemento", atc: "A11CC05" },
  { ai: "Carbonato de cálcio", tc: "Suplemento de cálcio/antiácido", atc: "A12AA04" },
  { ai: "Sulfato ferroso", tc: "Antianêmico (ferro)", atc: "B03AA07" },
  { ai: "Ácido fólico", tc: "Vitamina (folato)", atc: "B03BB01" },
  { ai: "Cianocobalamina (vitamina B12)", tc: "Vitamina", atc: "B03BA01" },
  // Imunossupressores / reumatologia
  { ai: "Ciclosporina", tc: "Imunossupressor", atc: "L04AD01" },
  { ai: "Tacrolimo", tc: "Imunossupressor", atc: "L04AD02" },
  { ai: "Hidroxicloroquina", tc: "Antirreumático/antimalárico", atc: "P01BA02" },
  { ai: "Leflunomida", tc: "Antirreumático modificador da doença (DMARD)", atc: "L04AA13" },
];
